### ISSUE TITLE
Support for proxy

### ISSUE THREAD

**Issue by yvz5** [newrelic/newrelic-telemetry-sdk-python#17]
Currently trying to use this sdk behind a corporate proxy. It doesnt recognize the environment variable set. Therefore it can not find the new relic api url. Are you planning of adding the proxy support ?

`<urllib3.connection.VerifiedHTTPSConnection object at 0x03AEE570>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed`

**Comment by a-feld** [comment]
Hi @yvz5 , adding some level of proxy support sounds like a good idea to me! I have to admit I'm pretty unfamiliar with how corporate proxies are usually configured. Would you mind providing some more information about your environment?

1. What OS are you using? (windows, linux, etc.)
1. You mention there are environment variables you're setting that you're expecting to configure the proxy. Which environment variables are these and what are they set to?
1. Any additional information that you can provide about the proxies themselves?

**Comment by yvz5** [comment]
Hi @a-feld, thanks for you reply. Proxy settings usually are OS agnostic and used as an envrionment variable.
```
HTTP_PROXY=http://localhost:3128
HTTPS_PROXY=http://localhost:3128
NO_PROXY=localhost
```
Above are the env variables that are set for the proxy. So you could  check if these variables exist and use a proxy manager. I saw that urllib3 has a ProxyManager.

Some people might not use a local proxy software and put their credentials in the env variable itself as follows:
```
HTTP_PROXY=username:password@proxy.com:8080
...
```
I dont know if that matters but good to keep in mind.

**Comment by xv1nx** [comment]
I am having the same issue. 
For urllib, one just need to set http_proxy and https_proxy as environment variables.
Any suggestion how to fix it? even if it is a dirty hack?

**Comment by vinh-cao** [comment]
This brings me further to next problem:
In file: https://github.com/newrelic/newrelic-telemetry-sdk-python/blob/master/src/newrelic_telemetry_sdk/client.py

`    def __init__(self, insert_key, host=None, port=443):
100         host = host or self.HOST
101         headers = self.HEADERS.copy()
102         headers.update(
103             {
104                 "Api-Key": insert_key,
105                 "Content-Encoding": "gzip",
106                 "Content-Type": "application/json",
107             }
108         )
109         retries = urllib3.Retry(
110             total=False, connect=None, read=None, redirect=0, status=None
111         )
112         proxy_header = urllib3.make_headers(proxy_basic_auth='ACCOUNT:PASSWORD') ## you can parse the https_proxy from os.environ.get('https_proxy','')
113         proxy_manager = urllib3.ProxyManager("http://IP-ADDRESS:8080/", headers=proxy_header)
114         self._pool = self.POOL_CLS(
115             host=host, port=port, retries=retries, headers=headers, strict=True,
116             _proxy=proxy_manager.proxy, _proxy_headers=proxy_header
117         )
`

There is a new problem for me:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/newrelic_airflow_plugin/harvester.py", line 67, in _loop
    response = client.send_batch(items, common=common)
  File "/usr/local/lib/python3.7/site-packages/newrelic_telemetry_sdk/client.py", line 179, in send_batch
    return self._pool.urlopen("POST", self.PATH, body=payload)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 930, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 494, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
urllib3.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

Some more information from this thread: https://discuss.newrelic.com/t/ssl-certificate-verify-failed-downgrade-certifi-package/34925/7

> Further experimentation with the above script shows the certificate fails to verify under certain combinations of urrllib3 prerequisites + newer certifi packages. Under the latest pyopenssl/etc. the cert verifies properly with any version of certifi.
