### ISSUE TITLE
broken links in readme

### ISSUE THREAD

**Issue by edmundadjei** [newrelic/newrelic-telemetry-sdk-python#42]
Most of the links to NewRelic documentation referenced in README are broken

e.g.

Find and use data
Tips on how to find and query your data in New Relic:

Find metric data
Find event data
Find log data
Find trace/span data
For general querying information, see:

Query New Relic data
Intro to NRQL

**Comment by bradleycamacho** [comment]
Hey @edmundadjei, thanks for reporting this! We have an ongoing incident with redirects on our docs site which is breaking these links. They should be fixed in the next couple of hours.
