### ISSUE TITLE
Harvester backtrace

### ISSUE THREAD

**Issue by droctothorpe** [newrelic/newrelic-telemetry-sdk-python#51]
I'm running into an issue where if the harvester thread fails it prints the backtrace to stdout once the process that spawned the thread completes.

I need harvester to fail silently.

How would I go about preventing the backtrace and [this](https://github.com/newrelic/newrelic-telemetry-sdk-python/blob/main/src/newrelic_telemetry_sdk/harvester.py#L83) log statement?

**Comment by droctothorpe** [comment]
Found a solution but it requires monkey patching the harvester module. I wonder if it makes sense to make this configurable. Would be happy to contribute a PR to that effect if you think it makes sense.

Hacky work-around for future reference:

```python
from newrelic_telemetry_sdk.harvester import _logger

_logger.exception = _logger.debug
_logger.error = _logger.debug
```

The above code makes errors silent by default, but you can enable debug logs to view them.

**Comment by a-feld** [comment]
Hey @droctothorpe ! While I no longer work for New Relic (and will most likely not be very responsive while I attend to my day job 😄), I came across this issue and wondered if I might be able to help out here.

The harvester [is using standard built-in Python logging](https://github.com/newrelic/newrelic-telemetry-sdk-python/blob/09474695eed4e49332da36e0619e2630ae83146c/src/newrelic_telemetry_sdk/harvester.py#L19) and therefore, as an example, the following solution should eliminate any logging outputs:
```python
import logging

# Adding a null logger here will drop all logs in py3+
# ensure this is called only once in your program to avoid adding multiple handlers
logging.getLogger("newrelic_telemetry_sdk.harvester").addHandler(logging.NullHandler())
# If using Python 2
logging.getLogger("newrelic_telemetry_sdk.harvester").setLevel(logging.CRITICAL)
```

Here's a complete example
```python
import logging
import time

from newrelic_telemetry_sdk import Harvester, MetricBatch, MetricClient

logging.getLogger("newrelic_telemetry_sdk.harvester").addHandler(logging.NullHandler())

metric_client = MetricClient("an_invalid_key_to_demonstrate_errors")
metric_batch = MetricBatch()
metric_batch.record_count("total", 1)
harvester = Harvester(metric_client, metric_batch, harvest_interval=1)
harvester.start()
time.sleep(1)
harvester.stop()
```

More information about the logging libraries used [can be found here](https://docs.python.org/3/howto/logging.html#logging-flow) and there are other solutions that could be applied as well, depending on your preferences for configuring logging.

Cheers!

**Comment by droctothorpe** [comment]
Thank you so much, @a-feld! That's an excellent, simple, and succinct solution. I really appreciate the time and effort you put into your response, especially the in-depth example. Thank you!
