### ISSUE TITLE
Tag mappings without a `copy` method raise an `AttributeError`

### ISSUE THREAD

**Issue by MrAlias** [newrelic/newrelic-telemetry-sdk-python#9]
I tried instrumenting an application using the [newrelic-opencensus-exporter-python](https://github.com/newrelic/newrelic-opencensus-exporter-python) package, but received the following traceback when sending a span:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/opencensus/common/transports/async_.py", line 112, in _thread_main
    self.exporter.emit(data)
  File "/usr/local/lib/python3.7/site-packages/opencensus_ext_newrelic/trace.py", line 103, in emit
    duration_ms=duration_ms,
  File "/usr/local/lib/python3.7/site-packages/newrelic_telemetry_sdk/span.py", line 68, in __init__
    attributes = tags and tags.copy() or {}
AttributeError: 'BoundedDict' object has no attribute 'copy'
```

This appears to be caused by the [choice made in the OpenCensus project](https://github.com/census-instrumentation/opencensus-python/pull/649/files#diff-62bd16ca571497fb0a37ef0894a260d1R240-R244) to use a non-`dict` type for attributes of a span. The `BoundedDict` class they use in this package does not support the `copy` method, therefore causing this `AttributeError` to be raised.

[A temporary fix](https://github.com/newrelic/newrelic-telemetry-sdk-python/commit/ce4e6da2d431841561294f5776b1909927f85982) was pushed to address this issue, but a more thorough investigation and possibly alternate solution were desired by @a-feld.

**Comment by a-feld** [comment]
Thanks for the report @MrAlias ! I have a PR open to fix this. After the fix is merged, we'll get a release out addressing this issue!
